"""Subtitle workspace package metadata and configuration schema."""

from app.modules.plugins.contracts import PluginManifest
from app.modules.plugins.permissions import PluginPermission

MANIFEST = PluginManifest(
    entrypoint="plugin:SubtitleWorkspacePlugin",
    id="subtitle-manager",
    name="字幕管理助手",
    version="1.0.0",
    description="在线搜索、自动匹配并管理媒体外挂字幕。",
    icon="mdi-subtitles-outline",
    permissions=(
        PluginPermission.ORGANIZER_HISTORY,
        PluginPermission.MEDIA_FILES_READ,
        PluginPermission.MEDIA_FILES_WRITE_SIDECAR,
        PluginPermission.NOTIFICATION_SEND,
    ),
    capabilities=(
        "plugin_page",
        "subtitle_sidecar",
        "online_subtitle",
        "transfer_assistant",
    ),
    events=("organizer.completed", "sync.completed", "metadata.scrape.completed"),
    frontend_module="frontend.js",
    navigation={
        "title": "字幕管理",
        "icon": "mdi-subtitles-outline",
        "section": "tools",
        "order": 65,
        "visibility_config_key": "show_sidebar_nav",
    },
    config_schema={
        "description_display": "hidden",
        "editor_height": 560,
        "layout": {"columns": 2, "row_gap": 14, "column_gap": 16},
        "sections": [
            {
                "key": "general",
                "title": "基础设置",
            },
            {
                "key": "online",
                "title": "在线字幕源",
            },
        ],
        "fields": [
            {
                "key": "show_sidebar_nav",
                "input_type": "switch",
                "label": "开启侧边菜单",
                "default": True,
                "description": "在侧边栏显示字幕管理入口；关闭不影响事件自动处理。",
                "section": "general",
            },
            {
                "key": "notification_enabled",
                "input_type": "switch",
                "label": "发送通知",
                "default": False,
                "description": "开启后发送字幕检查和文件操作结果。",
                "section": "general",
            },
            {
                "key": "default_language",
                "visible": False,
                "input_type": "select",
                "label": "默认字幕语言",
                "default": "auto",
                "description": ("上传默认自动识别；无法识别时需手动选择，不套用旧语言标记。"),
                "section": "general",
                "options": [
                    {"value": "auto", "label": "自动识别"},
                    {"value": "zh-CN", "label": "简体中文（zh-CN）"},
                    {"value": "zh-TW", "label": "繁体中文（zh-TW）"},
                    {"value": "zh", "label": "中文（zh）"},
                    {"value": "en", "label": "英语（en）"},
                    {"value": "ja", "label": "日语（ja）"},
                    {"value": "ko", "label": "韩语（ko）"},
                ],
            },
            {
                "key": "overwrite_existing",
                "input_type": "switch",
                "label": "允许覆盖同名字幕",
                "default": False,
                "description": "默认关闭，避免意外覆盖已经校对的字幕。",
                "section": "general",
            },
            {
                "key": "traditional_to_simplified",
                "input_type": "switch",
                "label": "繁体字幕转简体",
                "default": False,
                "description": "保存自动匹配的繁体中文字幕时转换为简体。",
                "section": "general",
            },
            {
                "key": "trigger_event",
                "input_type": "select",
                "label": "触发事件",
                "default": "",
                "description": ("仅为所选事件中的媒体搜索、下载并保存匹配字幕；不选择则关闭。"),
                "section": "general",
                "options": [
                    {"value": "", "label": "不启用"},
                    {"value": "organizer.completed", "label": "整理完成"},
                    {"value": "sync.completed", "label": "同步完成"},
                    {"value": "metadata.scrape.completed", "label": "刮削完成"},
                ],
            },
            {
                "key": "auto_skip_chinese_media_on_transfer",
                "input_type": "switch",
                "label": "自动跳过中文媒体",
                "default": True,
                "description": "中文原声媒体不自动搜索字幕，仍可在工作台手动处理。",
                "section": "general",
            },
            {
                "key": "auto_multi_subtitle_mode",
                "input_type": "select",
                "label": "多字幕处理",
                "default": "best",
                "description": "控制一次自动任务最多保留多少份候选字幕。",
                "section": "general",
                "options": [
                    {"value": "best", "label": "仅最佳字幕"},
                    {"value": "chinese_all", "label": "全部中文字幕"},
                    {"value": "all", "label": "全部字幕"},
                ],
            },
            {
                "key": "auto_subtitle_language_priority",
                "input_type": "textarea",
                "label": "语言优先级",
                "default": ["zh-CN-en", "zh-TW-en", "zh-CN", "zh-TW", "zh", "en"],
                "visible": False,
            },
            {
                "key": "auto_subtitle_format_priority",
                "input_type": "textarea",
                "label": "格式优先级",
                "default": ["ass", "ssa", "srt"],
                "visible": False,
            },
            {
                "key": "online_providers",
                "input_type": "select",
                "multiple": True,
                "label": "启用字幕源",
                "default": ["subhd", "zimuku"],
                "description": "可多选；搜索时会合并结果并按语言与格式排序。",
                "section": "online",
                "options": [
                    {"value": "subhd", "label": "SubHD"},
                    {"value": "zimuku", "label": "字幕库"},
                    {"value": "assrt", "label": "ASSRT"},
                    {"value": "opensubtitles", "label": "OpenSubtitles"},
                    {"value": "subdl", "label": "SubDL"},
                    {"value": "shooter", "label": "射手影音"},
                    {"value": "xunlei", "label": "迅雷看看"},
                ],
            },
            {
                "key": "subdl_api_key", "input_type": "password", "label": "SubDL API Key",
                "default": "", "secret": True, "encrypted": True, "section": "online",
                "description": "在 subdl.com 账户的 API 页面获取。",
            },
            {
                "key": "subdl_api_url", "input_type": "url", "label": "SubDL API 地址",
                "default": "https://api.subdl.com/api/v1", "section": "online",
            },
            {
                "key": "shooter_api_url", "input_type": "url", "label": "射手影音 API 地址",
                "default": "https://www.shooter.cn/api/subapi.php", "section": "online",
                "description": "按视频文件哈希匹配，支持本地视频和可访问、支持 Range 的 STRM 视频。",
            },
            {
                "key": "xunlei_api_url", "input_type": "url", "label": "迅雷看看 API 地址",
                "default": "http://sub.xmp.sandai.net:8000/subxl", "section": "online",
                "description": "按视频文件哈希匹配，支持本地视频和可访问、支持 Range 的 STRM 视频。",
            },
            {
                "key": "online_use_proxy",
                "input_type": "switch",
                "label": "在线搜索使用代理",
                "default": False,
                "description": "仅影响字幕源请求，不影响本地媒体文件读取。",
                "section": "online",
            },
            {
                "key": "subhd_url",
                "input_type": "url",
                "label": "SubHD 地址",
                "default": "https://subhd.tv",
                "section": "online",
            },
            {
                "key": "zimuku_url",
                "input_type": "url",
                "label": "字幕库地址",
                "default": "https://zmk.pw",
                "section": "online",
            },
            {
                "key": "assrt_api_key",
                "input_type": "password",
                "label": "ASSRT API Key",
                "default": "",
                "secret": True,
                "encrypted": True,
                "section": "online",
            },
            {
                "key": "auto_match_score",
                "input_type": "number",
                "label": "自动匹配最低分",
                "default": 75,
                "description": (
                    "自动事件只下载身份匹配分达到该值的候选，页面仍可预览全部合格候选。"
                ),
                "section": "general",
                "validation": {"minimum": 50, "maximum": 100},
            },
            {
                "key": "assrt_search_url",
                "input_type": "url",
                "label": "ASSRT 手动搜索地址",
                "default": "https://2.assrt.net",
                "section": "online",
            },
            {
                "key": "assrt_api_url",
                "input_type": "url",
                "label": "ASSRT API 地址",
                "default": "https://api.assrt.net/v1",
                "section": "online",
            },
            {
                "key": "opensubtitles_api_key",
                "input_type": "password",
                "label": "OpenSubtitles API Key",
                "default": "",
                "secret": True,
                "encrypted": True,
                "section": "online",
            },
            {
                "key": "opensubtitles_api_url",
                "input_type": "url",
                "label": "OpenSubtitles API 地址",
                "default": "https://api.opensubtitles.com/api/v1",
                "section": "online",
            },
            {
                "key": "opensubtitles_username",
                "input_type": "text",
                "label": "OpenSubtitles 用户名",
                "default": "",
                "section": "online",
            },
            {
                "key": "opensubtitles_password",
                "input_type": "password",
                "label": "OpenSubtitles 密码",
                "default": "",
                "secret": True,
                "encrypted": True,
                "section": "online",
            },
        ],
    },
)
