from app.modules.plugins.contracts import PluginManifest
from app.modules.plugins.permissions import PluginPermission
from .event_refresh import REFRESH_EVENT, SOURCE_EVENTS

manifest = PluginManifest(
    entrypoint="plugin:CastProfileEnricherPlugin",
    id="cast-profile-enricher",
    name="演职员资料完善",
    version="1.0.1",
    description="补充影视人物的中文姓名、简介、角色信息与头像。",
    icon="mdi-account-star-outline",
    permissions=(
        PluginPermission.MEDIA_SERVER_READ,
        PluginPermission.MEDIA_SERVER_WRITE_METADATA,
        PluginPermission.MEDIA_SERVER_WRITE_IMAGES,
        PluginPermission.MEDIA_DISCOVER,
    ),
    capabilities=("metadata_enricher", "media_server_controller", "scheduled_task"),
    schedule_seconds=24 * 60 * 60,
    events=(*SOURCE_EVENTS, REFRESH_EVENT),
    frontend_module="frontend.js",
    config_schema={
        "description_display": "hidden",
        "layout": {"columns": 2, "row_gap": 14, "column_gap": 16},
        "editor_width": 900,
        "fields": [
            {
                "key": "enabled",
                "input_type": "switch",
                "label": "启用定时生成",
                "default": False,
                "description": "按执行周期自动扫描媒体库；关闭后仍可手动执行。",
                "icon": "mdi-calendar-clock",
            },
            {
                "key": "cron",
                "input_type": "cron",
                "label": "执行周期",
                "default": "",
                "placeholder": "5位cron表达式，留空自动",
                "description": "留空时每天运行一次。首次处理大型媒体库可能耗时较长。",
                "icon": "mdi-calendar-clock",
            },
            {
                "key": "trigger_event",
                "input_type": "select",
                "label": "触发事件",
                "default": "",
                "description": "不选择时关闭事件触发；整理和同步完成需确保已有元数据。",
                "icon": "mdi-lightning-bolt-outline",
                "options": [
                    {"value": "", "label": "不启用"},
                    {"value": "organizer.completed", "label": "整理完成"},
                    {"value": "sync.completed", "label": "同步完成"},
                    {"value": "metadata.scrape.completed", "label": "刮削完成"},
                ],
            },
            {
                "key": "scrape_delay",
                "input_type": "number",
                "label": "触发后延迟执行（秒）",
                "default": 60,
                "description": "等待媒体服务器读取媒体及元数据后再更新人物资料。",
                "validation": {"minimum": 0, "maximum": 3600},
            },
            {
                "key": "selected_servers",
                "input_type": "resource_multi_select",
                "resource_kind": "media_server",
                "required_capabilities": ["read", "write_metadata"],
                "label": "媒体服务器",
                "default": [],
                "description": "未选择时处理全部已启用的媒体服务器。",
            },
            {
                "key": "condition",
                "input_type": "select",
                "label": "处理范围",
                "default": "missing_any",
                "description": "建议选择“姓名或角色未中文化”，避免重复改写已有资料。",
                "icon": "mdi-filter-outline",
                "options": [
                    {"value": "all", "label": "全部人物"},
                    {"value": "missing_any", "label": "姓名或角色未中文化"},
                    {"value": "missing_name", "label": "姓名未中文化"},
                    {"value": "missing_role", "label": "角色未中文化"},
                ],
            },
            {
                "key": "update_biography",
                "input_type": "switch",
                "label": "补充人物简介",
                "default": True,
                "description": "为缺少简介的人物写入可用的中文资料。",
                "icon": "mdi-text-box-edit-outline",
            },
            {
                "key": "remove_unresolved",
                "input_type": "switch",
                "label": "移除无法完善的人物",
                "default": False,
                "description": "仅在两个资料源均无法找到可靠匹配时移除，默认关闭。",
                "icon": "mdi-account-off-outline",
            },
        ],
    },
)
